### ISSUE TITLE
Error disallowed_useragent

### ISSUE THREAD

**Issue by zuku81** [noinnion/greader#285] opened 2017-06-15 21:02 UTC
I'm trying to login using google to my feedly feeds Andrzej gry error disallowed_useragent. I'm using latest pro version.

**Comment by christianmenkens** [comment] 2017-06-16 13:44
Same problem here ... can't login with Google anymore.

**Comment by CommanderBond** [comment] 2017-06-22 06:04
Same here. I thought this had something to do with my new handset (Samsung Galaxy S8). When connecting gReader with Feedly using Google OAuth, this error occurs:
![greader google oauth error](https://user-images.githubusercontent.com/12641279/27419451-58299d02-5721-11e7-916a-191a31a09473.png)

**Comment by FoxBJK** [comment] 2017-06-22 11:44
Same on my Nexus 5X. I used my Google account to set up Feedly, so now I can't use this app

**Comment by CommanderBond** [comment] 2017-06-22 11:49
You can use Feely using another authentication provider as a workaround: Log in to Feedly using your web browser, go to your profile and add another login (Feedly, Twitter …).

**Comment by zuku81** [comment] 2017-06-22 11:50
are any developers here, do you gonna fix this issue? 
I paid for Pro version of greader and can't use it.

**Comment by bderiso** [comment] 2017-08-03 14:35
Duplicate of issue #278

Please comment there for increased visibility (although it seems like this project is abandoned anyway).

There is a workaround in the comments of that issue as well.

**Closed** 2021-09-20 20:17 UTC
