### ISSUE TITLE
Network error (expected ':status' header not present) 

### ISSUE THREAD

**Issue by camisotro** [noinnion/greader#344] opened 2018-02-21 12:43 UTC
Lately I've been getting the above error almost every time I sync on WiFi whether at home or the office. For whatever reason sync works on mobile data but not WiFi. Any insights?

**Comment by camisotro** [comment] 2018-02-21 12:44
![screenshot_20180221-074132](https://user-images.githubusercontent.com/9795642/36480637-0e06ff9c-16db-11e8-9b54-37ed38f6726c.png)

**Comment by Ack0** [comment] 2018-02-21 21:19
Same here.
God, save us.

**Comment by klausw** [comment] 2018-02-22 03:05
Getting the same error on various WiFi networks and LTE, haven't been able to log in recently. Is there any additional debug info that could help?

Initially I was using Google login where I got this error on trying to reload. I also set up a Feedly account but that still gets the same error.

**Comment by fabiohl** [comment] 2018-02-22 04:40
Same here. Happening on wi-fi and 4G, since very early today....
Version 4.3.1_Pro (April 2016!!!!)
I'm reading some reviews in the Google Play Store acking the software is abandoned......

**Comment by c8c8** [comment] 2018-02-22 06:52
You can bypass this by logging out and then logging back into Feedly again but this time click the 3 dots in the upper right corner and uncheck the "https" sign-in option. The good news is that everything will work again. The bad news is that your login is no longer secure. Sadly, it looks like the beginning of the end for this once great but now dead for years project. Time to start looking for something comparable. There sure aren't a lot of quality choices.

**Comment by Ack0** [comment] 2018-02-22 12:12
> There sure aren't a lot of quality choices.

That is the problem. 

If anyone find a real alternative, please share. I tried a lot of apps, but they are really slow in comparison.

**Comment by camisotro** [comment] 2018-02-22 12:12
Hmm trying that, but now Google login won't work.
![screenshot_20180222-071149](https://user-images.githubusercontent.com/9795642/36537971-c53b2dea-179f-11e8-9061-7c94cab2173c.png)

**Comment by wmill** [comment] 2018-02-22 14:53
+1

**Comment by jasonimani** [comment] 2018-02-22 17:31
I had the same problem. What I did to resolve this is to export my rss feeds (opml) from Feedly and create an account on Feedly without Google. Import opml files, and then login from Greader with your new account.

Alternatively, in your account settings in Feedly, you can link accounts and create a login. I noticed this feature after I had already done the above. If someone could try it and let us know.

**Comment by camisotro** [comment] 2018-02-22 17:36
I linked my existing account to Facebook and then logged back into gReader that way.

**Comment by klausw** [comment] 2018-02-22 17:46
@jasonimani and @camisotro , which error were you getting? This bug is intended for the ":status header not present" error. The "Error: disallowed user agent" issue already has issues #338 and #343, it's confusing if they get mixed together here. I don't think that the workaround of linking a different account type helps for the ":status header not present" error.

@jasonimani , FYI, creating a new Feedly account and linking it in Feedly fixed the "disallowed user agent" error, but I'm still stuck at the ":status header not present" error, I get this after attempting to login with the Feedly account.

As a side note, I'm now using the Feedly Android app which works OK, though I preferred GReader.

**Comment by camisotro** [comment] 2018-02-22 17:51
Sorry to clarify, I attempted the suggested workaround to the error for this issue, and then when trying to log in I ran into the user agent issue. I bypassed the latter by linking a different account type.

I think the reason we're all seeing the user agent issue too is, many of us logged into gReader years ago and haven't attempted to reauthenticate since before that was an issue.

**Comment by jasonimani** [comment] 2018-02-22 17:51
@klausw Sorry you're correct. There are two issues and should be in separate threads.

Initially, my problem was the topic of this forum (Network error (expected ':status' header not present). In an attempt to troubleshoot, I logged out...among many other ideas.

Which led to the Google authentication issue.

Sorry to hear that the solution I posted didn't fix the issue for you.

**Comment by BarDick** [comment] 2018-02-22 18:37
The same issue. 
It is very great when the community tries to help resolving the problem. But what about developers?
 Or buying a Pro version is money for nothing?

**Comment by c8c8** [comment] 2018-02-22 21:28
gReader was abandoned years ago; it remains the best, but it's dead as projects go. The developer did the same with News+ in 2015. 

I'm enjoying NewsJet as an alternative RSS reader. Fast, free, beautiful dark theme, and a great internal browser. It's pretty simple and the Pocket integration could be better, but at least it still appears alive.

**Comment by rootex-** [comment] 2018-02-23 08:08
Same story, same error... Never had any issues since moving all my RSS data from Google (since Google auth was broken) to a separate Feedly account. But this is one is tough 🤔

**Comment by rootex-** [comment] 2018-02-23 08:25
@Ack0, can confirm. But not for all VPNs. US didn't work for me, but UK did. Thank you!

**Comment by mariozhivago** [comment] 2018-02-24 14:26
Any one managed to fix it? I've logged out and not I can't not log in.. Using newsjet in the meantime but isn't the same :(

**Comment by rootex-** [comment] 2018-02-24 14:32
@mariozhivago the same happened to me. You may try to reinstall and will be automatically logged in once you launch the app. This worked for me all the time. FYI, I was also already logged in into my Feedly app and a Feedly account in Chrome. Possibly, it takes login context from Chrome on the fly 🤔

**Comment by mariozhivago** [comment] 2018-02-25 23:06
@rootex- unfortunately didn't work..

**Comment by mariozhivago** [comment] 2018-02-25 23:06
But thank you

**Comment by c8c8** [comment] 2018-02-25 23:11
It's an https error.  Turn off the https and the error is gone.

**Comment by takueof** [comment] 2018-02-26 15:37
Please FIX this bug!
I'm PRO version user.
If the bug isn't fixed, I will request a refund procedure from Google.

**Comment by wmill** [comment] 2018-02-26 16:05
It's strange that it broke so suddenly. Did Feedly start using HTTP2? Or was it an Android update?

**Comment by rootex-** [comment] 2018-02-26 18:24
@wmill I don't think it's and Android update since the problem appeared the last week. How do I turn off https?

**Comment by rootex-** [comment] 2018-02-26 18:26
@mariozhivago you may try turning on VPN then, this thing really helps.

**Comment by LaughingJohn** [comment] 2018-02-27 08:45
Just thought I'd add my voice to this one. I have recent install on a new phone. Works fine over 4g, but broken over WiFi. Tried uninstalling, clearing cache etc. I'm logging in with a feedly account because of the other issue with google accounts.
Shame as I really like this app, tried the feedly app but couldn't get on with it (dark theme isn't as good and I don't like the lack of continuous scrolling}.

**Comment by rootex-** [comment] 2018-02-27 10:20
@LaughingJohn it does not work over my 4g, VPN needed for both cases

**Comment by Origen17** [comment] 2018-02-27 14:55
Same here - problem just cropped up two days ago on Feedly Pro Android.  WiFi or 4G either one.  Reinstalling didn't help.  Is it time to look for a new RSS app for my Feedly account?

**Comment by dswisher** [comment] 2018-02-27 14:59
I worked around this by creating a feedly account, linking that to my google account within feedly, then logging into gReader using the feedly account with https disabled.

See #278 for additional details.

**Comment by Origen17** [comment] 2018-02-27 15:20
Update - I have a Feedly login - I just logged out and back in again with HTTPS disabled - works fine.

**Comment by rootex-** [comment] 2018-02-27 15:36
@Origen17 did this solve the issue with receiving RSS feed updates? Or just the login issue itself?

**Comment by Origen17** [comment] 2018-02-27 15:38
I'm not familiar with that issue - I don't have it myself.

**Comment by rootex-** [comment] 2018-02-27 15:50
@Origen17 it is strange you don't have issues with feed updates

**Comment by Origen17** [comment] 2018-02-27 15:52
I don't see that listed in this thread - what is going on?

**Comment by rootex-** [comment] 2018-02-27 15:55
@Origen17 I am talking about the network error on trying to sync rss feed. Please look through the top post of this thread

**Comment by Origen17** [comment] 2018-02-27 15:58
Right - that is what me and dswisher corrected as logged above.

**Comment by rootex-** [comment] 2018-02-27 16:03
@Origen17 OK, once again. Did this solve the greader sync issue and you are now able to receive updates via wifi and mobile network without any errors?

**Comment by Origen17** [comment] 2018-02-27 16:08
Yes it did - I was never talking about the login issue.

**Comment by allante2** [comment] 2018-02-27 16:57
@Origen17 -- how to you disable HTTPS from the Feedly or GReader apps?  I don't see any such option in the Settings menu.  Thank you.

**Comment by Origen17** [comment] 2018-02-27 17:05
Logout.  Then at the login dialogue, there is a menu at the top right.  Uncheck it in that menu.

**Comment by rootex-** [comment] 2018-02-27 17:09
![](https://i.imgur.com/kVzlm0s.jpg)

**Comment by Pcsl** [comment] 2018-02-27 18:22
If this project was alive I would never post this but even if I loved gReader and was my favorite app, it seems it's time to start using a different client.

I tried most of them and I think most of you will like FeedMe and Palabre. Both are good and quite customizable. FeedMe is even open source. They are not as perfect as gReader was but it seems is time to move.

**Comment by rootex-** [comment] 2018-02-27 18:35
I've tried a couple of dozens rss readers. None of them have such perfect widgets like this... ![](https://i.imgur.com/k76nG9O.jpg)![](https://i.imgur.com/OjVrbQh.jpg)

**Comment by mrfuxi** [comment] 2018-02-27 20:24
I had this issue for the most of the day today, however, somehow it just worked from mobile but not from the tablet.

While being annoyed at gReader I started to look for alternative and found [FeedMe](https://play.google.com/store/apps/details?id=com.seazon.feedme). Looks oddly similar to gReader and it's being actively developed (last release 24 Feb) it's free and has no ads. It's a good idea to donate something to support the guy! My plan is to move to that app permanently.

**Comment by LaughingJohn** [comment] 2018-02-27 20:50
Just got home from work and oddly it seems to be working now on WiFi. Maybe it's something feedly are doing..

**Comment by hville** [comment] 2018-02-27 21:58
I had the same problem and somehow after a few hours all is working again. Possibly the issue was not with greader.

**Comment by mariozhivago** [comment] 2018-02-27 22:03
Yes it worked... Thank you guys.

**Comment by Ack0** [comment] 2018-02-28 01:17
Using any app with VPN functionality will bypass this problem. Confirmed it right now with NetGuard.

**Comment by noinnion** [comment] 2021-03-01 08:30
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue

**Closed by noinnion** 2021-03-01 08:30 UTC
