### ISSUE TITLE
Scrolling with finger on YouTube pane

### ISSUE THREAD

**Issue by RedSkyRoad** [noinnion/greader#194] opened 2016-07-08 06:01 UTC
When scrolling a page with your finger on a YouTube pane causes it to open the video. This is not suppose to happen. Only tapping a video should open one. Not scrolling

**Comment by colmbuckley** [comment] 2016-07-09 11:56
Yes, this is happening to me also. It's quite annoying - the most common action I'm now performing is closing the YouTube window...

Hope this can get fixed soon.

**Comment by leyton01** [comment] 2016-07-15 09:33
Same problem here - hoping for a fix.

**Comment by johndoppke** [comment] 2016-07-16 19:27
Same for me. Also, every time I play a YouTube video (intentionally or unintentionally), then hit the back button, within a second the video pops up again and I have to hit the back button again. Wondering if maybe it is responding to both "action down" and "action up" touch events? I'm no Android expert but something like that might explain both the overly sensitive response to scrolling as well as the double playing of the video (both of which began at the same time for me).

Thanks in advance for looking into this!

**Comment by jdaverth** [comment] 2016-07-17 00:00
Just an FYI, this is a duplicate of https://github.com/noinnion/greader/issues/189 -- Still no acknowledgement on that issue either though.

**Comment by RedSkyRoad** [comment] 2016-07-18 15:38
This needs to be fixed now. It's getting fucking annoying

**Comment by jdaverth** [comment] 2016-08-03 02:09
More than a month since the original issue (189) was opened and not even an acknowledgement of the bug.  At this point, I'm starting to think it is a feature.  Has anyone else jumped to another reader yet?  I'm looking for recommendations.

**Comment by WCityMike** [comment] 2016-09-30 17:37
Disappointed to see no fix, but I'm unsurprised -- I believe I remember the developer saying somewhere that this is a dead project. (Credit that with all the weight of a third-hand vague remembrance, i.e., none.)

That having been said, one suggested workaround: use the volume buttons, as opposed to a finger swipe, to scroll previous-next. It does not seem to trigger this bug.

**Comment by vakasoft** [comment] 2016-10-21 10:15
I hate this . Disable the autoplay please

**Comment by hofst** [comment] 2016-11-26 17:54
This is a duplicate of #189

**Closed** 2021-09-20 20:18 UTC
