### ISSUE TITLE
Google login issue error 403 auth issue

### ISSUE THREAD

**Issue by chirba4** [noinnion/greader#280] opened 2017-06-04 21:01 UTC
I can't login using my Google aching
Account I get an authentication error
Please fix

**Comment by basaner** [comment] 2017-06-05 07:37
Me too.

"403. That’s an error.

Error: disallowed_useragent"

**Comment by maltus** [comment] 2017-06-06 19:21
Me either. can not use gReader on android

**Comment by oreillygshane** [comment] 2017-06-07 00:19
Same issue

**Comment by nixxo** [comment] 2017-06-09 07:40
same issue.

**Comment by jetinski** [comment] 2017-06-12 11:30
same here. can not login to greader using "feedly cloud -> continue with google "

**Comment by jetinski** [comment] 2017-06-13 07:01
quick fix: add a "feedly login" under manage account -> logins on feedly.com so you can login with username and password instead of a third-party provider

**Comment by gromlix** [comment] 2017-06-30 19:36
Google changed prohibits the use of webview componet for oauth now.

https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html
https://www.theregister.co.uk/2016/08/23/google_to_block_web_views_from_using_its_oauth/

Please fix!

**Comment by Spoker** [comment] 2017-07-03 08:02
Same problem here.

**Comment by geekscrapy** [comment] 2017-07-04 11:32
Same problems here, was just about to buy greader, but if it's this well supported...

**Comment by jandruu** [comment] 2017-07-10 12:20
I just got the same error as you all. Hope they fix it soon.

**Comment by bimoap** [comment] 2017-07-25 06:52
Same here. 
Feedly Cloud -> Login -> Continue with Google ->
Error 403
Error: disallowed_useragent

All my subscriptions is in my Google account.

**Comment by QBKay** [comment] 2017-07-30 18:24
Same here...

**Comment by bderiso** [comment] 2017-08-03 14:37
Duplicate of issue #278

Please comment there for increased visibility (although it seems like this project is abandoned anyway).

There is a workaround in the comments of that issue as well.

**Comment by holla2040** [comment] 2017-09-01 22:26
same problem here.

**Comment by humphreysb** [comment] 2017-09-09 15:03
Same problem here

**Comment by spoilerhead** [comment] 2017-09-09 15:56
FYI, I switched to Palabre and it works much better.

Am 09.09.2017 17:04 schrieb "Brad Humphreys" <notifications@github.com>:

**Comment by shin701** [comment] 2017-10-01 14:45
same problem....

**Comment by paternostre** [comment] 2017-10-21 10:55
Workaround for problem with Google login. 

On a desktop computer, do this: 

1) create new Feedly login at feedly.com (so NOT google but FEEDLY, the type af login with a password)  
2) login again at feedly.com with your google login
3) link your new feedly account to your google account
4) at your android device, login to gReader wirt your new Feedly account (preferences -> logins)

**Comment by kodedylf** [comment] 2017-12-05 11:39
Same problem here

**Comment by SaadBilal** [comment] 2018-05-24 19:21
Same issue, anyone go some solution?

**Comment by aff-tar** [comment] 2018-06-14 03:53
Same for me. Should we expect for a fix?

**Comment by timtang2010** [comment] 2018-09-09 00:43
Log in via the feedly account

**Comment by timtang2010** [comment] 2018-09-09 00:44
Greadet is not maintained, the software is also off the shelf

**Comment by noinnion** [comment] 2021-02-28 08:40
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue

**Closed by noinnion** 2021-02-28 08:40 UTC
