### ISSUE TITLE
Images missing from Cached view

### ISSUE THREAD

**Issue by apatternjugglers** [noinnion/greader#62] opened 2015-08-22 05:17 UTC
Hi -I did check for existing issues, but the once that seemed a bit similar were not the same as I am finding.
I find that with many feeds that the images are missing in Cached view, despite being present in Feed view.
One current example is the article at 
 http://www.theverge.com/2015/8/21/9189833/android-google-phones-apps-bloatware
In feed view I see the image of an android phone screen, followed by the text content, but in cached view the image is missing.  -It seems the same on most (but not all) other feeds.
I definitely have the setting for Cache Feed Images in Offline Content set, but it doesn't have the effect I expect.
The behaviour seems the same on my poor 4 year old 4.03 tablet as it is on my 5.1 phone (and yes I'm ecstatic that Greader pro still works well on both!)

**Comment by whimboo** [comment] 2015-09-05 17:38
Dupe of issue #16?

**Comment by noinnion** [comment] 2016-04-01 21:20
What Android version do you have? Is Storage permission enabled?
Settings->App->gReader->Permissions

please try the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

**Comment by noinnion** [comment] 2021-02-28 07:47
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue

**Closed by noinnion** 2021-02-28 07:47 UTC
Labels: duplicate
