### ISSUE TITLE
Can't log in with goole

### ISSUE THREAD

**Issue by mdvl** [noinnion/greader#307] opened 2017-08-21 21:18 UTC
Error 403. Disallowed user agent

**Comment by mvolz** [comment] 2017-08-23 21:21
I am experiencing the same issue. I get a 403 user agent disallowed error.

**Comment by mvolz** [comment] 2017-08-23 21:24
Dupe of issue #278

**Comment by svysik** [comment] 2017-08-28 21:26
Same issue when trying to sign into Feedly with Google account on the pro version and free version

**Comment by noinnion** [comment] 2021-02-28 07:45
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue

**Closed by noinnion** 2021-02-28 07:45 UTC
