### ISSUE TITLE
Google login issues

### ISSUE THREAD

**Issue by oreillygshane** [noinnion/greader#279] opened 2017-06-03 12:07 UTC
Getting an error when I try use Google Auth to signin to my feedly account.

**Comment by oreillygshane** [comment] 2017-06-03 12:08
"This user-agent is not permitted to make an OAuth authorization request to Google as it is classified as an embedded user-agent (also known as a web-view). Per our policy, only browsers are permitted to make authorization requests to Google. We offer several libraries and samples for native apps to perform authorization requests in the browser."

**Comment by Jiaming-Liu** [comment] 2017-06-24 17:29
same issue here.

**Comment by dee9062** [comment] 2017-06-24 17:54
same issue here (Android 7.1.1.)

**Comment by mcmonkeys1** [comment] 2017-07-06 08:47
Error: disallowed_useragent

This user-agent is not permitted to make an OAuth authorization request to Google as it is classified as an embedded user-agent (also known as a web-view). Per our policy, only browsers are permitted to make authorization requests to Google. We offer several libraries and samples for native apps to perform authorization requests in the browser.

**Comment by bderiso** [comment] 2017-08-03 14:37
Duplicate of issue #278

Please comment there for increased visibility (although it seems like this project is abandoned anyway).

There is a workaround in the comments of that issue as well.

**Comment by noinnion** [comment] 2021-03-01 08:39
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue

**Closed by noinnion** 2021-03-01 08:39 UTC
