### ISSUE TITLE
Login with Google not working anymore

### ISSUE THREAD

**Issue by bgmf** [noinnion/greader#283] opened 2017-06-13 05:33 UTC
First: thanks for the great app! Using it for years now.
But when I moved to my new Huawei Mate 9 and wanted to login with freshly via Google, I got the following error message: 

403. That’s an error.

Error: disallowed_useragent

This user-agent is not permitted to make an OAuth authorization request to Google as it is classified as an embedded user-agent (also known as a web-view). Per our policy, only browsers are permitted to make authorization requests to Google. We offer several libraries and samples for native apps to perform authorization requests in the browser.

Learn more

Request Details
That’s all we know.

Any way to fix that?

**Comment by Feoni4** [comment] 2017-06-14 04:38
Hello! I'm experiencing the same bug. It appears during auth in feedly using google account.
Waiting for a fast fix.

**Comment by Samunosuke** [comment] 2017-06-14 17:45
Hello! I got the same problem OAUTH is no more  possible by using a webview. Please fix it, I am using the PRO version for several years and I don't want search for another one.

**Comment by Zintag** [comment] 2017-06-15 09:07
![screenshot_20170615-105844](https://user-images.githubusercontent.com/29451681/27174011-d52fc5fe-51ba-11e7-8128-66a141e7aba5.png)
Having the same problem and came in to talk about that. 

If it helps (but I don't think so) I'm on a xperia z3 compact (D5803) and Android version is 6.0.1 (it's up to date, at least regarding this device).

Trying to log to Feedly using google. Can post several screens if needed.

**Comment by Janzstone** [comment] 2017-06-15 12:07
I'm having the same issue. Was going to purchase the app but since it's not even functional ATM I guess I'll have to look elsewhere.

**Comment by jessejhein** [comment] 2017-06-18 03:58
One of my most used apps, but doing a clean install went to retrieve my feedly feed and then login via Google. Same error.

**Comment by Feoni4** [comment] 2017-06-19 07:14
You can add logn + passwd to your account in feedly and login with them in greader.
Just tempotary solution

**Comment by vossim** [comment] 2017-06-24 08:50
I have the same issue, would be great to see a solution to this.

**Comment by mikeflandro** [comment] 2017-07-03 18:58
Same issue. Don't want to use the Feedly app. Please fix

**Comment by calciphus** [comment] 2017-07-19 15:56
Same issue, now over a month old.

**Comment by FranzSchenk** [comment] 2017-07-24 12:08
Same here. Is there anybody out there ???

**Comment by calciphus** [comment] 2017-07-24 17:38
@FranzSchenk I ended up switching apps. https://play.google.com/store/apps/details?id=com.levelup.palabre seems to have much more responsive devs

**Comment by vincentw56** [comment] 2017-07-24 17:41
@calciphus Thanks, I will look into it. You can't really say they are more responsive since they haven't updated their app since Dec 15, 2016.

**Comment by calciphus** [comment] 2017-07-24 17:46
@vincentw56 That's when Google changed their OAuth policies. https://stackoverflow.com/questions/40591090/403-error-thats-an-error-error-disallowed-useragent

A month of a broken app I paid for means I have to look for something that works. Someone who updated when this changed is more responsive. 

Removing the link to a competing product out of courtesy. Thank you for looking into the matter.

**Comment by bderiso** [comment] 2017-08-03 14:36
Duplicate of issue #278

Please comment there for increased visibility (although it seems like this project is abandoned anyway).

There is a workaround in the comments of that issue as well.

**Comment by egiesem** [comment] 2018-06-18 14:39
solved
https://www.youtube.com/watch?v=vFSgIdtEl2k

**Comment by noinnion** [comment] 2021-02-28 08:40
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue

**Closed by noinnion** 2021-02-28 08:40 UTC
