### ISSUE TITLE
blank screen after returning from website

### ISSUE THREAD

**Issue by tmartin67** [noinnion/greader#114] opened 2016-01-21 00:01 UTC
When I navigate from article view to the website and then press back to reaffirm to the article view it is fully black.

**Comment by nyn3x** [comment] 2016-01-21 21:54
I noticed this too. Started a couple of days ago.

**Comment by RedSkyRoad** [comment] 2016-01-22 15:31
Same here

**Comment by UkropCanada** [comment] 2016-01-23 23:01
Same here. Very annoying...

**Comment by aappii** [comment] 2016-01-28 07:52
Me too. 
The issue is also described in #115.

**Comment by Stift** [comment] 2016-01-30 18:11
For me it seems, when the advertisement is loaded the screen gets somehow messed up. Very very annoying and reproducable.

**Comment by rudyych** [comment] 2016-02-10 10:01
Same here.

Google Nexus 5x, gReader Pro

**Comment by ajoe** [comment] 2016-02-20 11:06
Turning off hardware acceleration works for me.

**Comment by Stift** [comment] 2016-03-02 22:59
But this could not be the real solution?

**Comment by RedSkyRoad** [comment] 2016-03-03 02:52
Can we PLEASE get this fixed now

**Comment by ajoe** [comment] 2016-03-19 09:44
GReader is DEAD!  
Developer doesn't answer to mails. Website http://noinnion.com/greader is down since a couple months (03/2016). I liked it, but there is no source code public available. 
My alternatives that I found good:

Palabre - RSS-Reader (2,40 € to remove Add's)
https://play.google.com/store/apps/details?id=com.levelup.palabre

Antennapod - Podcast (OSS - Open Source Software)
https://play.google.com/store/apps/details?id=de.danoeh.antennapod

**Comment by noinnion** [comment] 2016-03-26 21:30
please try the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

**Comment by RedSkyRoad** [comment] 2016-03-27 07:28
This issue has been resolved but now some feeds just don't load

**Comment by noinnion** [comment] 2016-03-27 21:32
please tell me the feeds

**Comment by RedSkyRoad** [comment] 2016-03-28 03:38
A lot of feeds. Attached is all I'm getting. It opens perfectly in
Chrome...

http://feedproxy.google.com/~r/Techcrunch/~3/yGk__PH2up0/
On 27 Mar 2016 23:32, "noinnion" <notifications@github.com> wrote:

please tell me the feeds

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/noinnion/greader/issues/114#issuecomment-202148297>

**Comment by RedSkyRoad** [comment] 2016-03-28 03:39
This app is busy wasting my time...

**Comment by Stift** [comment] 2016-03-29 10:36
@noinnion Could you please give an update on the current status of this app? The website is down, there was no reaction since months, ppl started looking for alternatives. And out of a sudden comes a new beta. Could you elaborate this a little bit, maybe in a separate issue?

**Comment by noinnion** [comment] 2016-03-30 08:37
website is online again. the app will be updated more frequently. sorry for
the abstinence.

**Comment by Stift** [comment] 2016-03-30 09:18
Thanx for taking this up again and I really appreciate your answers. Also these you give here: https://groups.google.com/forum/#!topic/g_reader/tZh9lqiyVdE

**Closed** 2016-03-31 14:28 UTC
