### ISSUE TITLE
YouTube videos are playing automatically when scrolling

### ISSUE THREAD

**Issue by andyd0** [noinnion/greader#214] opened 2016-09-10 13:57 UTC
Hi.  This has been going on for some time now.  I thought it was due to accidental clicking but looks like whenever there is a YouTube video embedded on the page it will play automatically.  Not sure if this is due to caching but found myself having to quickly close out of the app so the video doesn't play

**Comment by McPostal** [comment] 2016-10-13 03:23
Yes. And now I have to back out of the YouTube video 3 times before it stops reloading.

**Comment by vakasoft** [comment] 2016-10-21 10:12
I hate this. Please disable the auto play

**Comment by andyd0** [comment] 2016-10-21 15:02
When you say autoplay, do you mean in the YouTube app?

**Comment by seanfitzz** [comment] 2016-10-23 07:36
Sample URL: http://feedproxy.google.com/~r/readwriteweb/~3/m3Z_vJyBNJo/

Same YouTube video pops up 3x while scrolling

**Comment by varnion** [comment] 2016-10-27 04:31
I'm also being affected by this bug. is so annoying having to close the video 3 TIMES all the time

**Comment by Nekmo** [comment] 2016-11-02 15:15
This is horrible. Please fix it.

**Comment by andyd0** [comment] 2016-11-03 00:50
I thought vakasoft was the developer commenting but I realize now that it was just another comment.  The most annoying part about this is that autoplays and starts eating at data.

**Comment by roflomglol** [comment] 2016-11-17 13:15
God it's annoying, please do something about it!

**Comment by cpinter** [comment] 2016-11-17 14:17
+1 Please fix! I'm afraid of youtube videos now

**Comment by hofst** [comment] 2016-11-26 17:49
This is so annyoing it wants me to punsh the app every time it happens...!

**Comment by hofst** [comment] 2016-11-26 17:55
This is a duplicate of #189 and #194

**Comment by aisbergde** [comment] 2016-12-11 09:42
Most time it happens when I am scrolling and tap on the YouTube picture without intent. I want to feature request a context menu item "open in YouTube" when I long press the YouTube image. Why I don't use the built-in viewer? Because I want to be able to switch optionally to the YouTube app to like it there or to share directly from YouTube

**Comment by LaughingJohn** [comment] 2017-01-08 12:08
Love this app, but this is the most annoying bug. Pretty sure it was introduced in a "recent" update..

**Comment by pearson** [comment] 2017-03-19 04:23
It would be nice if there was an option to disable the YouTube playing on touch. It is far too easy to touch a video when scrolling, and then have to hit back three times to return to gReader. It wouldn't be so bad if it only required one back press...

And it's MUCH worse if the option to launch the YouTube app for playback is selected. Having the actual YouTube app launch three times is simply painful.

**Comment by moonspell13** [comment] 2017-08-20 15:13
+1 
Fix bug, please.
:'(

**Comment by noinnion** [comment] 2021-02-28 08:42
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue

**Closed by noinnion** 2021-02-28 08:42 UTC
