### ISSUE TITLE
Feedly через Google 

### ISSUE THREAD

**Issue by ViX7** [noinnion/greader#293] opened 2017-07-03 03:51 UTC
НЕ РАБОТАЕТ АУТЕНТИФИКАЦИЯ В FEEDLY ЧЕРЕЗ GOOGLE!!!! ЧТО-ТО ДЕЛАТЬ СОБИРАЕТЕСЬ? УЖЕ ПИСАЛ. НИ ОТВЕТА, НИ ПРИВЕТА.

**Comment by bderiso** [comment] 2017-08-03 14:35
Duplicate of issue #278

Please comment there for increased visibility (although it seems like this project is abandoned anyway).

There is a workaround in the comments of that issue as well.

**Comment by bderiso** [comment] 2017-08-03 15:14
Here is a workaround from taschmidt; this worked for me. Sorry I can't speak Russian :)
"FYI, I got around this by going to feedly.com from a desktop browser and creating an actual Feedly account. Then log out of that account, log back in with your Google account and link that Feedly account (somewhere in the account preferences screens). Then you can log into gReader using your newly created Feedly credentials and you're good to go."

**Comment by noinnion** [comment] 2021-02-28 08:45
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue

**Closed by noinnion** 2021-02-28 08:45 UTC
